[tool.poetry]
name = "balaton-game-backend"
version = "0.1.1"
description = ""
authors = ["Timothy.Ram"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
